### Base de Dados

**Input**: 
* YYYYMMDD.csv - retornos de todas ações listadas na NYSE na frequência de um minuto do dia DD-MM-YYYY.

**Output**: 
* YYYYMMDD_x.csv - retornos com as três primeiras defasagens de todas ações listadas na NYSE na frequência de um minuto do dia DD-MM-YYYY.
* YYYYMMDD_y.csv - retornos de 250 ações escolhidas aleatóriamente do dia DD-MM-YYYY.

Neste notebook, nosso objetivo será pegar uma base de dados de um determinado dia contendo o retorno de ações listadas na NYSE da Trade and Quote (TAQ). Esses dados estão armazenados no DropBox com a extensão .mat (arquivo MATLAB). Para podermos ler o arquivo em python, teremos que fazer um processo de conversão dos dados no programa MATLAB de .mat para .csv (quando estivermos prontos para puxar toda base de dados podemos criar um loop em MATLAB que faça isso).

Cada base de dados é referente a um dia cujo formato do nome do arquivo é YYYYMMDD.csv contendo o horário como índice na forma HHMMSS e os símbolos das ações como colunas. Cada entrada representa o retorno em um minuto da respectiva ação no respectivo minuto.

O output desse notebook será dois arquivos csv's, um contendo 250 ações que servirão como preditivas e o outro contendo os retornos de todas ações defasados em até três períodos.

In [1]:
# pacotes
import numpy as np
import pandas as pd

In [2]:
# oculta mensagens de avisos
import warnings
warnings.filterwarnings("ignore")

In [3]:
# cria um dataframe a partir do csv de um dia de retornos
df = pd.read_csv('../../input/data/1min/by_date/20030102.csv', index_col=0)

In [4]:
df

,A,AA,AAAB,AAC,AACE,AAI,AAII,AAME,AANB,AAON,...,ZNT,ZOLL,ZOLT,ZOMX,ZONA,ZONS,ZOOM,ZQK,ZRAN,ZTEL
Time,,,,,,,,,,,,,,,,,,,,,
93100,0.000000,0.002602,0.0,0.0,0.0,0.017790,-0.000702,0.0,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.016667,-0.140357
93200,0.001645,-0.001734,0.0,0.0,0.0,0.000000,0.002735,0.0,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,-0.002068,0.000000
93300,0.005464,0.002167,0.0,0.0,0.0,0.000000,-0.002033,0.0,0.0,0.000000,...,-0.000424,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,-0.002073,0.000000
93400,-0.001091,0.000865,0.0,0.0,0.0,0.000000,0.001403,0.0,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000371,0.005724,0.000000
93500,0.000000,0.000000,0.0,0.0,0.0,0.000000,-0.001403,0.0,0.0,0.000000,...,0.000000,0.000000,-0.045462,0.000000,0.000000,0.0,0.0,0.000370,-0.007800,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155600,0.000000,-0.000424,0.0,0.0,0.0,0.002378,-0.003503,0.0,0.0,0.000000,...,0.000417,0.000274,0.000000,0.013423,0.000000,0.0,0.0,0.001096,0.001655,0.000000
155700,-0.001043,0.000000,0.0,0.0,0.0,-0.002378,0.001403,0.0,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000730,-0.001655,0.000000
155800,0.000000,-0.000848,0.0,0.0,0.0,0.000000,-0.000701,0.0,0.0,0.000000,...,0.000000,-0.000274,0.000000,0.000000,0.000000,0.0,0.0,0.000365,0.006605,0.000000
155900,-0.001044,0.001272,0.0,0.0,0.0,0.000000,-0.001052,0.0,0.0,0.000000,...,0.000000,-0.000521,0.000000,0.000000,0.000000,0.0,0.0,0.000000,-0.000659,0.000000
160000,0.000000,-0.002121,0.0,0.0,0.0,0.000000,-0.004573,0.0,0.0,0.039586,...,0.000000,-0.000027,0.000000,0.000000,0.000962,0.0,0.0,-0.000730,0.000659,0.000000

In [5]:
# escolhendo 250 ações para usar como base preditiva
np.random.seed(0)
random_colnames = np.random.choice(df.columns, 250, replace = False)

In [6]:
# criando dataframe com as ações escolhidas aleatoriamente
pred_df = df[random_colnames]

In [7]:
# adicionar (t) no nome das colunas
for col in pred_df.columns:
    pred_df.rename(columns = {'%s'%(col):'%s(t)'%(col)}, inplace=True);

In [8]:
pred_df

,IFUL(t),RMD(t),NI(t),HYSQ(t),HSC(t),ACDO(t),GNLB(t),DRVR(t),BJCT(t),SP(t),...,BPRX(t),DLX(t),RRGB(t),PLUM(t),CALA(t),DHB(t),RRA(t),RMHT(t),FDTR(t),DRRX(t)
Time,,,,,,,,,,,,,,,,,,,,,
93100,0.0,0.000000,0.001001,-0.011561,0.000000,-0.000284,0.000000,0.0,0.0,0.000000,...,0.015456,0.000119,-0.021070,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.023867
93200,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,-0.011990,0.0,0.0,0.000000,...,-0.000844,-0.000119,0.000000,0.000000,0.0,0.002972,0.000000,0.000000,0.0,0.000000
93300,0.0,0.000000,0.001000,0.011561,0.000939,-0.000851,0.023551,0.0,0.0,0.000000,...,-0.016952,0.000000,0.000000,0.000000,0.0,-0.002972,0.000000,0.000000,0.0,0.000000
93400,0.0,0.000000,0.000499,0.000000,0.000313,-0.000568,0.005731,0.0,0.0,0.003069,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,-0.004728
93500,0.0,0.000000,0.000000,0.000000,0.000000,-0.001421,-0.028988,0.0,0.0,0.000000,...,0.000000,-0.000953,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155600,0.0,0.000000,-0.001956,-0.000602,0.000000,-0.001103,0.000000,0.0,0.0,-0.001043,...,0.000000,0.000238,-0.000039,0.000000,0.0,0.000000,0.002732,0.000000,0.0,0.000000
155700,0.0,0.000322,0.000489,0.000000,0.001547,0.000000,0.000000,0.0,0.0,-0.001044,...,0.003656,0.000000,0.000039,0.000000,0.0,0.000000,0.004084,0.007737,0.0,0.000000
155800,0.0,0.000000,-0.000979,0.000000,0.000927,0.000000,0.000000,0.0,0.0,0.000000,...,-0.001461,-0.000238,0.004294,0.003824,0.0,0.000000,0.000000,-0.007737,0.0,0.000000
155900,0.0,0.000645,0.002934,0.000000,-0.000618,-0.001656,0.000000,0.0,0.0,0.000000,...,0.000000,0.000238,-0.016893,0.011197,0.0,0.006192,0.000000,0.000000,0.0,0.000000
160000,0.0,0.000322,0.002925,0.000000,0.000309,0.001656,0.000000,0.0,0.0,0.001044,...,-0.002195,0.000476,0.000000,-0.000189,0.0,-0.006192,0.005420,0.012542,0.0,0.009479

In [9]:
# loop para adicionar (t) ao nome da coluna e adicionar três defasagens
for col in df.columns:
    for i in range(1,4):
        df["%s(t-%s)"%(col, i)] = df[col].shift(i)
    df = df.drop(col, axis=1)

In [10]:
df

,A(t-1),A(t-2),A(t-3),AA(t-1),AA(t-2),AA(t-3),AAAB(t-1),AAAB(t-2),AAAB(t-3),AAC(t-1),...,ZOOM(t-3),ZQK(t-1),ZQK(t-2),ZQK(t-3),ZRAN(t-1),ZRAN(t-2),ZRAN(t-3),ZTEL(t-1),ZTEL(t-2),ZTEL(t-3)
Time,,,,,,,,,,,,,,,,,,,,,
93100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93200,0.000000,NaN,NaN,0.002602,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,0.000000,NaN,NaN,0.016667,NaN,NaN,-0.140357,NaN,NaN
93300,0.001645,0.000000,NaN,-0.001734,0.002602,NaN,0.0,0.0,NaN,0.0,...,NaN,0.000000,0.000000,NaN,-0.002068,0.016667,NaN,0.000000,-0.140357,NaN
93400,0.005464,0.001645,0.000000,0.002167,-0.001734,0.002602,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.000000,-0.002073,-0.002068,0.016667,0.000000,0.000000,-0.140357
93500,-0.001091,0.005464,0.001645,0.000865,0.002167,-0.001734,0.0,0.0,0.0,0.0,...,0.0,0.000371,0.000000,0.000000,0.005724,-0.002073,-0.002068,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155600,0.000000,0.000522,0.000000,0.001696,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.000000,-0.000596,0.001923,0.000000,0.000000,0.000000,0.000000
155700,0.000000,0.000000,0.000522,-0.000424,0.001696,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.001096,0.000000,0.000000,0.001655,-0.000596,0.001923,0.000000,0.000000,0.000000
155800,-0.001043,0.000000,0.000000,0.000000,-0.000424,0.001696,0.0,0.0,0.0,0.0,...,0.0,0.000730,0.001096,0.000000,-0.001655,0.001655,-0.000596,0.000000,0.000000,0.000000
155900,0.000000,-0.001043,0.000000,-0.000848,0.000000,-0.000424,0.0,0.0,0.0,0.0,...,0.0,0.000365,0.000730,0.001096,0.006605,-0.001655,0.001655,0.000000,0.000000,0.000000
160000,-0.001044,0.000000,-0.001043,0.001272,-0.000848,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000365,0.000730,-0.000659,0.006605,-0.001655,0.000000,0.000000,0.000000

In [11]:
pred_df.to_csv('..\..\output\data\\20030102_y.csv', sep=',', encoding='utf-8')

In [12]:
df.to_csv('..\..\output\data\\20030102_x.csv', sep=',', encoding='utf-8')